# Generated by Django 5.1 on 2024-10-01 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='concert',
            name='band_name',
        ),
        migrations.AddField(
            model_name='concert',
            name='band',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='concerts.band'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='supporting_acts',
            field=models.ManyToManyField(blank=True, related_name='opened_for', to='concerts.band'),
        ),
    ]
