# Generated by Django 5.1 on 2024-10-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_band_remove_concert_band_name_concert_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(verbose_name='concert date'),
        ),
    ]
